export { default as reduce } from './reduce';
export { default as run } from './run';
export { default as pipe } from './pipe';
export { Maybe, Just, Nothing, lift } from './maybe';
export { Either, identity, revoke, truth, isUndefined } from './either';
export { default as list } from './list';
export { isIterable, ternary, sleep, mixin, attach } from './utils';
export { default as Fromise } from './fromise';
export { Any, All } from './semigroup';
export { default as isFunction } from './isFunction';
export { isFalsy, isNotFalsy } from './isFalsy';
export { default as isFalse } from './isFalse';
export { __true, __false } from './true-false';
